# Generated by Django 3.2.9 on 2021-11-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
    ]
