# Generated by Django 3.2.9 on 2021-11-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/boards/cover/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
