# Generated by Django 3.2.9 on 2021-11-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0002_auto_20211127_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cover',
        ),
    ]
