# Generated by Django 3.2.9 on 2021-11-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Boards', '0002_remove_board_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/boards/cover/'),
        ),
    ]
