# Generated by Django 3.2.9 on 2021-11-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_auto_20211128_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
    ]
