# Generated by Django 3.2.9 on 2021-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_remove_board_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/boards/cover/'),
        ),
    ]
