# Generated by Django 3.2.9 on 2021-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0004_auto_20211128_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/boards/cover/'),
        ),
    ]
