# Generated by Django 3.2.9 on 2021-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0004_board_cover'),
        ('Boards', '0006_board_created_by'),
    ]

    operations = [
    ]
