# Generated by Django 3.2.9 on 2021-11-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0004_alter_pin_attachment'),
        ('Boards', '0007_merge_0004_board_cover_0006_board_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, null=True, to='Pins.Pin'),
        ),
    ]
