# Generated by Django 3.2.9 on 2021-11-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user_id',
        ),
    ]
