# Generated by Django 3.2.9 on 2021-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0002_remove_board_pins'),
        ('Pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='boards',
            field=models.ManyToManyField(to='Boards.Board'),
        ),
    ]
