# Generated by Django 3.2.9 on 2021-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
        ('Categories', '0001_initial'),
        ('Pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='boards',
            field=models.ManyToManyField(blank=True, null=True, to='Boards.Board'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='Categories.Category'),
        ),
    ]
