# Generated by Django 3.2.9 on 2021-11-28 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pins', '0002_remove_pin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
    ]
