# Generated by Django 3.2.9 on 2021-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0003_pin_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='attachment',
            field=models.ImageField(null=True, upload_to='uploads/pins/'),
        ),
    ]
