# Generated by Django 3.2.9 on 2021-11-21 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
                ('pin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='comments_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin')),
            ],
            options={
                'verbose_name_plural': 'comments_likes',
            },
        ),
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin')),
            ],
            options={
                'verbose_name_plural': 'comments_reply',
            },
        ),
    ]
