# Generated by Django 3.2.9 on 2021-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'comments_reply',
            },
        ),
        migrations.CreateModel(
            name='comments_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'comments_likes',
            },
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
