# Generated by Django 3.2.9 on 2021-11-21 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0002_auto_20211121_2048'),
        ('Pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments_likes',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments'),
        ),
        migrations.AddField(
            model_name='comments_likes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin'),
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments'),
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin'),
        ),
    ]
