# Generated by Django 3.2.9 on 2021-11-21 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pins', '0001_initial'),
        ('Comments', '0002_auto_20211121_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comments',
            name='pin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='comments_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin')),
            ],
            options={
                'verbose_name_plural': 'comments_likes',
            },
        ),
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.comments')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin')),
            ],
            options={
                'verbose_name_plural': 'comments_reply',
            },
        ),
    ]
