# Generated by Django 3.2.9 on 2021-11-21 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0002_auto_20211121_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_content',
        ),
        migrations.AddField(
            model_name='comments',
            name='pin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pins.pin'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
