# Generated by Django 3.2.9 on 2021-11-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_comment_reply_comments_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_reply',
            options={'verbose_name_plural': 'comments_reply'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
