# Generated by Django 3.2.9 on 2021-11-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
