# Generated by Django 3.2.9 on 2021-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211120_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='User/cover'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.TextField(choices=[('arabic', 'ar'), ('english', 'en')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='User/profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronoun',
            field=models.TextField(choices=[('he', 'He'), ('she', 'She')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_google',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
