# Generated by Django 3.2.9 on 2021-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '__first__'),
        ('Users', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(null=True, to='Categories.Category'),
        ),
    ]
