# Generated by Django 3.2.9 on 2021-11-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_board',
        ),
    ]
