# Generated by Django 3.2.9 on 2021-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.JSONField(null=True),
        ),
    ]
