# Generated by Django 3.2.9 on 2021-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.JSONField(default={'categories': []}, null=True),
        ),
    ]
