# Generated by Django 3.2.9 on 2021-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '__first__'),
        ('Users', '0006_delete_user_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='Categories.Category'),
        ),
    ]
