# Generated by Django 3.2.9 on 2021-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.JSONField(default={'recent_categories': []}, null=True),
        ),
    ]
