# Generated by Django 3.2.9 on 2021-11-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
    ]
