# Generated by Django 3.2.9 on 2021-11-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20211120_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_conf',
            field=models.CharField(default='', max_length=255),
        ),
    ]
