# Generated by Django 3.2.9 on 2021-11-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_relationship'),
        ('Users', '0011_user_history'),
        ('Users', '0011_user_password_conf'),
    ]

    operations = [
    ]
