# Generated by Django 3.2.9 on 2021-11-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('Boards', '0001_initial'),
        ('Users', '0012_merge_20211121_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(to='Categories.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='Users.Relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boards.board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.CharField(max_length=250, null=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('user_board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user_board')),
            ],
        ),
    ]
