# Generated by Django 3.2.9 on 2021-11-23 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
        ('Users', '0013_auto_20211121_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='user_board_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boards.board'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='can_edit',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='collaborator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='User_board',
        ),
    ]
