# Generated by Django 3.2.9 on 2021-11-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20211123_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
