# Generated by Django 3.2.9 on 2021-11-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20211123_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
