# Generated by Django 3.2.9 on 2021-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_invitation_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Invitations',
            field=models.ManyToManyField(to='Users.Invitation'),
        ),
    ]
