# Generated by Django 3.2.9 on 2021-11-23 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_remove_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='Users.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
